SELECT 
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    _fivetran_synced AS _FIVETRAN_SYNCED_TS,
    REQUEST_AT AS REQUEST_TS,
    CAST(CLIENT_ID AS VARCHAR) AS CLIENT_ID,
    NAME,
    ADDRESS,
    CITY,
    PHONE,
    CAST(PET_ID AS VARCHAR) AS PET_ID, 
    PET_NAME,
    REQUEST_DAY_FROM AS REQUEST_WALK_TS,
    REQUEST_DURATION
FROM {{ source('gdrive', 'requests') }} 